routes/web.php
	<?php
Route::model('post','App\Post');
Route::model('event','App\Event');
Route::model('category','App\Category');
Route::model('type','App\Type');
Route::model('accommodation','App\Accommodation');
Route::model('service','App\Service');
Route::model('staff','App\Staff');
Route::model('user','App\User');
Route::model('term','App\Term');
Route::model('icon','App\Icon');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::get('/', ['as'=>'index', 'uses'=>'FrontendController@index']);
Route::get('/terms', ['as'=>'terms', 'uses'=>'FrontendController@terms']);
Route::get('attractions', ['as'=>'blog', 'uses'=>'FrontendController@blog']);
Route::get('attractions/category/{slug}', ['as'=>'blog.category', 'uses'=>'FrontendController@blogCategory']);
Route::get('attractions/post/{slug}', ['as'=>'blog.show', 'uses'=>'FrontendController@post']);

Route::get('news', ['as'=>'news', 'uses'=>'FrontendController@news']);

Route::get('galleries', ['as'=>'galleries', 'uses'=>'FrontendController@galleries']);

Route::get('event/{slug}', ['as'=>'events.show', 'uses'=>'FrontendController@eventSlug']);
Route::get('events', ['as'=>'events', 'uses'=>'FrontendController@events']);

Route::get('accommodation/{slug}', ['as'=>'room.accommodation', 'uses'=>'FrontendController@accommodation']);

Route::get('booking', ['as'=>'booking', 'uses'=>'FrontendController@booking']);

Route::get('about', ['as'=>'about', 'uses'=>'FrontendController@about']);

Route::get('contact', ['as'=>'contact', 'uses'=>'FrontendController@contact']);

Route::get('location', ['as'=>'location', 'uses'=>'FrontendController@location']);
Route::post('sendContact', ['as'=>'send.mail', 'uses'=>'FrontendController@postContact']);

//switch language. Default is english
Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);

Route::group(['middleware'=>'SentinelGuest'],function(){
	Route::get('login',['as'=>'login','uses'=>'Auth\LoginController@getSignin']);
	Route::post('postSignin', ['as'=>'postSignin'  ,'uses'=>'Auth\LoginController@postSignin']);
	Route::get('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
	Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
	Route::get('password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
	Route::post('password/reset', ['as' => 'password.request', 'uses' => 'Auth\ResetPasswordController@reset']);
});

Route::group(['middleware'=>'SentinelUser'],function(){
	Route::get('logout',['as'=>'logout','uses'=>'Auth\LoginController@getLogout']);

	Route::group(['prefix'=>'admin','as'=>'dash.'],function(){
		Route::get('/',['as'=>'index','uses'=>'DashboardController@index']);
		
		Route::group(['prefix'=>'posts','as'=>'post.'],function(){
			Route::get('/',['as'=>'index','uses'=>'PostController@index']);	
			Route::get('create',['as'=>'create','uses'=>'PostController@create']);
			Route::post('store',['as'=>'store','uses'=>'PostController@store']);
			Route::get('show/{post}',['as'=>'show','uses'=>'PostController@show']);	
			Route::get('edit/{post}',['as'=>'edit','uses'=>'PostController@edit']);	
			Route::put('update/{post}',['as'=>'update','uses'=>'PostController@update']);
			Route::get('delete/{post}',['as'=>'delete','uses'=>'PostController@destroy']);	
		});

		Route::group(['prefix'=>'categories','as'=>'category.'],function(){
			Route::get('/',['as'=>'index','uses'=>'CategoryController@index']);	
			Route::get('create',['as'=>'create','uses'=>'CategoryController@create']);
			Route::post('store',['as'=>'store','uses'=>'CategoryController@store']);
			Route::get('show/{category}',['as'=>'show','uses'=>'CategoryController@show']);	
			Route::get('edit/{category}',['as'=>'edit','uses'=>'CategoryController@edit']);	
			Route::put('update/{category}',['as'=>'update','uses'=>'CategoryController@update']);
			Route::get('delete/{category}',['as'=>'delete','uses'=>'CategoryController@destroy']);	
		});

		Route::group(['prefix'=>'events','as'=>'event.'],function(){
			Route::get('/',['as'=>'index','uses'=>'EventController@index']);	
			Route::get('create',['as'=>'create','uses'=>'EventController@create']);
			Route::post('store',['as'=>'store','uses'=>'EventController@store']);
			Route::get('show/{event}',['as'=>'show','uses'=>'EventController@show']);	
			Route::get('edit/{event}',['as'=>'edit','uses'=>'EventController@edit']);	
			Route::put('update/{event}',['as'=>'update','uses'=>'EventController@update']);
			Route::get('delete/{event}',['as'=>'delete','uses'=>'EventController@destroy']);	
		});

		Route::group(['prefix'=>'galleries','as'=>'gallery.'],function(){
			Route::get('/',['as'=>'index','uses'=>'GalleryController@index']);	
			Route::get('create',['as'=>'create','uses'=>'GalleryController@create']);
			Route::post('store',['as'=>'store','uses'=>'GalleryController@store']);
			Route::get('show/{gallery}',['as'=>'show','uses'=>'GalleryController@show']);	
			Route::get('edit/{gallery}',['as'=>'edit','uses'=>'GalleryController@edit']);	
			Route::put('update/{gallery}',['as'=>'update','uses'=>'GalleryController@update']);
			Route::get('delete/{gallery}',['as'=>'delete','uses'=>'GalleryController@destroy']);	
		});


		Route::group(['prefix'=>'accommodations','as'=>'accommodation.'],function(){
			Route::get('/',['as'=>'index','uses'=>'AccommodationController@index']);	
			Route::get('create',['as'=>'create','uses'=>'AccommodationController@create']);
			Route::post('store',['as'=>'store','uses'=>'AccommodationController@store']);
			Route::get('show/{accommodation}',['as'=>'show','uses'=>'AccommodationController@show']);	
			Route::get('edit/{accommodation}',['as'=>'edit','uses'=>'AccommodationController@edit']);	
			Route::put('update/{accommodation}',['as'=>'update','uses'=>'AccommodationController@update']);
			Route::get('delete/{accommodation}',['as'=>'delete','uses'=>'AccommodationController@destroy']);	
		});

		Route::group(['prefix'=>'typeaccommodations','as'=>'type_accommodation.'],function(){
			Route::get('/',['as'=>'index','uses'=>'TypeController@index']);	
			Route::get('create',['as'=>'create','uses'=>'TypeController@create']);
			Route::post('store',['as'=>'store','uses'=>'TypeController@store']);
			Route::get('show/{type}',['as'=>'show','uses'=>'TypeController@show']);	
			Route::get('edit/{type}',['as'=>'edit','uses'=>'TypeController@edit']);	
			Route::put('update/{type}',['as'=>'update','uses'=>'TypeController@update']);
			Route::get('delete/{type}',['as'=>'delete','uses'=>'TypeController@destroy']);	
		});

		Route::group(['prefix'=>'services','as'=>'service.'],function(){
			Route::get('/',['as'=>'index','uses'=>'ServiceController@index']);	
			Route::get('create',['as'=>'create','uses'=>'ServiceController@create']);
			Route::post('store',['as'=>'store','uses'=>'ServiceController@store']);
			Route::get('show/{service}',['as'=>'show','uses'=>'ServiceController@show']);	
			Route::get('edit/{service}',['as'=>'edit','uses'=>'ServiceController@edit']);	
			Route::put('update/{service}',['as'=>'update','uses'=>'ServiceController@update']);
			Route::get('delete/{service}',['as'=>'delete','uses'=>'ServiceController@destroy']);	
		});

		Route::group(['prefix'=>'staffs','as'=>'staff.'],function(){
			Route::get('/',['as'=>'index','uses'=>'StaffController@index']);	
			Route::get('create',['as'=>'create','uses'=>'StaffController@create']);
			Route::post('store',['as'=>'store','uses'=>'StaffController@store']);
			Route::get('show/{staff}',['as'=>'show','uses'=>'StaffController@show']);	
			Route::get('edit/{staff}',['as'=>'edit','uses'=>'StaffController@edit']);	
			Route::put('update/{staff}',['as'=>'update','uses'=>'StaffController@update']);
			Route::get('delete/{staff}',['as'=>'delete','uses'=>'StaffController@destroy']);	
		});

		Route::group(['prefix'=>'users','as'=>'user.'],function(){
			Route::get('/',['as'=>'index','uses'=>'UserController@index']);	
			Route::get('create',['as'=>'create','uses'=>'UserController@create']);
			Route::post('store',['as'=>'store','uses'=>'UserController@store']);
			//Route::get('show/{user}',['as'=>'show','uses'=>'UserController@show']);	
			Route::get('edit/{user}',['as'=>'edit','uses'=>'UserController@edit']);	
			Route::put('update/{user}',['as'=>'update','uses'=>'UserController@update']);
			Route::get('delete/{user}',['as'=>'delete','uses'=>'UserController@destroy']);	
			//Route::get('restore/{id}', array('as' => 'restore', 'uses' => 'UserController@restore'));
		});

		//role
		Route::group(['prefix'=>'roles','as'=>'role.'], function(){
			Route::get('/', array('as' => 'index', 'uses' => 'RoleController@index'));
			Route::get('create', array('as' => 'create', 'uses' => 'RoleController@create'));
			Route::post('store', array('as' => 'store', 'uses' => 'RoleController@store'));
			Route::get('edit/{id}', array('as' => 'edit', 'uses' => 'RoleController@edit'));
			Route::put('update/{id}', array('as' => 'update', 'uses' => 'RoleController@update'));
			Route::get('delete/{id}', array('as' => 'delete', 'uses' => 'RoleController@destroy'));
		});

		Route::group(['prefix'=>'terms','as'=>'term.'],function(){
			Route::get('/',['as'=>'index','uses'=>'TermController@index']);	
			Route::get('create',['as'=>'create','uses'=>'TermController@create']);
			Route::post('store',['as'=>'store','uses'=>'TermController@store']);
			Route::get('show/{term}',['as'=>'show','uses'=>'TermController@show']);	
			Route::get('edit/{term}',['as'=>'edit','uses'=>'TermController@edit']);	
			Route::put('update/{term}',['as'=>'update','uses'=>'TermController@update']);
			Route::get('delete/{term}',['as'=>'delete','uses'=>'TermController@destroy']);	
		});

		Route::group(['prefix'=>'icons','as'=>'icon.'],function(){

resources/views/admin/configuration.blade.php
@extends('admin/layouts/default')

@section('css')
@endsection

@section('body')
<main>
	<div class="breadcrumb grey lighten-3">
		<h6>Configurações</h6>
	</div>

	<div class="container section">
		<div class="row">
			<form method="post" class="col s12" action="{{ route('dash.config.store') }}">
				{{ csrf_field() }}
				<div class="row">
					<div class="input-field col s12">
						<input id="name" type="text" name="name" value="{{$configuration->name}}">
						<label for="name">Nome</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="rss" type="text" name="rss" value="{{$configuration->rss}}">
						<label for="rss">RSS</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="facebook" type="text" name="facebook" value="{{$configuration->facebook}}">
						<label for="facebook">Facebook</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="instagram" type="text" name="instagram" value="{{$configuration->instagram}}">
						<label for="instagram">Instagram</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="twitter" type="text" name="twitter" value="{{$configuration->twitter}}">
						<label for="twitter">Twitter</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="gplus" type="text" name="gplus" value="{{$configuration->gplus}}">
						<label for="gplus">Google Plus</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="city" type="text" name="city" value="{{$configuration->cidade}}">
						<label for="city">Cidade</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="state" type="text" name="state" value="{{$configuration->estado}}">
						<label for="state">Estado</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="country" type="text" name="country" value="{{$configuration->pais}}">
						<label for="country">País</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="address" type="text" name="address" value="{{$configuration->endereco}}">
						<label for="address">Endereço</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="number" type="text" name="number" value="{{$configuration->numero}}">
						<label for="number">Número</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="neighborhood" type="text" name="neighborhood" value="{{$configuration->bairro}}">
						<label for="neighborhood">Bairro</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="zip" type="text" name="zip" value="{{$configuration->cep}}">
						<label for="zip">CEP</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="beach" type="text" name="beach" value="{{$configuration->praia}}">
						<label for="beach">Praia</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="phone" type="text" name="phone" value="{{$configuration->telefone}}">
						<label for="phone">Telefone</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="whatsapp" type="text" name="whatsapp" value="{{$configuration->whatsapp}}">
						<label for="whatsapp">Whatsapp</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input id="email" type="text" name="email" value="{{$configuration->email}}">
						<label for="email">E-mail</label>
					</div>
				</div>

				<div class="row center">
					<div class="col s12">
						<button class="waves-effect btn black-text" type="submit">Enviar</button>
					</div>
				</div>
			</form> 
		</div>
	</div>
</main>
@endsection

@section('script')
@endsection

resources/views/admin/index.blade.php
@extends('admin/layouts/default')

@section('css')
@endsection

@section('body')
<main>
	<div class="breadcrumb grey lighten-3">
		<h6>Dashboard</h6>
	</div>

	<div class="notifications">
		@include('errors/notifications')
	</div>
	
	<div class="container">		
		<div class="row">
			<div class="col s12 m6 l4">
				<a href="{{ route('dash.post.index') }}">
					<div class="card z-depth--1 black-text">				
						<h3 class="center"><i class="material-icons large">description</i></h3>
						<h5 class="center">Postagens</h5>
					</div>
				</a>
			</div>
			<div class="col s12 m6 l4">
				<a href="{{ route('dash.event.index') }}">
					<div class="card z-depth--1 black-text">				
						<h2 class="center"><i class="material-icons large">event</i></h2>
						<h5 class="center">Eventos</h5>
					</div>
				</a>
			</div>
			<div class="col s12 m6 l4">
				<a href="{{ route('dash.gallery.index') }}">
					<div class="card z-depth--1 black-text">				
						<h2 class="center"><i class="material-icons large">collections</i></h2>
						<h5 class="center">Galeria de fotos</h5>
					</div>
				</a>
			</div>
			<div class="col s12 m6 l4">
				<a href="{{ route('dash.accommodation.index') }}">
					<div class="card z-depth--1 black-text">				
						<h2 class="center"><i class="material-icons large">hotel</i></h2>
						<h5 class="center">Acomodações</h5>
					</div>
				</a>
			</div>
			<div class="col s12 m6 l4">
				<a href="{{ route('dash.staff.index') }}">
					<div class="card z-depth--1 black-text">				
						<h2 class="center"><i class="material-icons large">people</i></h2>
						<h5 class="center">Staff</h5>
					</div>
				</a>
			</div>
			<div class="col s12 m6 l4">
				<a href="{{ route('dash.config') }}">
					<div class="card z-depth--1 black-text">				
						<h2 class="center"><i class="material-icons large">settings</i></h2>
						<h5 class="center">Configurações</h5>
					</div>
				</a>
			</div>
			<div class="col s12 m6 l4">
				<a href="{{ route('dash.role.index') }}">
					<div class="card z-depth--1 black-text">				
						<h2 class="center"><i class="material-icons large">lock</i></h2>
						<h5 class="center">Permissões</h5>
					</div>
				</a>
			</div>
			<div class="col s12 m6 l4">
				<a href="{{ route('dash.user.index') }}">
					<div class="card z-depth--1 black-text">				
						<h2 class="center"><i class="material-icons large">people_outline</i></h2>
						<h5 class="center">Usuários</h5>
					</div>
				</a>
			</div>
			<div class="col s12 m6 l4">
				<a href="{{ route('logout') }}">
					<div class="card z-depth--1 black-text">				
						<h2 class="center"><i class="material-icons large">exit_to_app</i></h2>
						<h5 class="center">Sair</h5>
					</div>
				</a>
			</div>
		</div>
	</div>
</main>
@endsection

@section('script')
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>Dashboard login</title>
	<meta content="width=device-width, initial-scale=1" name="viewport"/>
	<meta content="" name="description"/>
	<meta content="" name="author"/>
	<meta name="theme-color" content="#212121" />

	<link rel="stylesheet" href="{{ asset('css/materialize.css') }}">
	<link rel="stylesheet" href="{{ asset('css/login.css') }}">
	<link rel="stylesheet" href="{{ asset('css/font-awesome.min.css') }}">
</head>
<body>
	<div class="content">
		<div class="row">
			<form class="col s12 m5 offset-m3 l4 offset-l4" method="post" action="{{ route('postSignin')}}">
				{{csrf_field()}}
				<img src="../images/logo.svg" alt="Canguru Hostel" class="logo">
				<div class="notifications">
					@include('errors/notifications')
				</div>
				<div class='row'>
					<div class='input-field col s12'>
						<input class='validate' type='email' name='email' id='email' />
						<label for='email'>Usuário</label>
					</div>
				</div>

				<div class='row'>
					<div class='input-field col s12'>
						<input class='validate' type='password' name='password' id='password' />
						<label for='password'>Senha</label>
					</div>
				</div>

				<center>
					<div class='row'>
						<button type='submit' name='btn_login' class='btn black-text waves-effect'>Login</button>
					</div>
				</center>
			</form>
		</div>
	</div>

	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script src="{{ asset('js/materialize.js') }}"></script>
</body>
</html>