routes/web.php
	<?php
Route::model('post','App\Post');
Route::model('event','App\Event');
Route::model('category','App\Category');
Route::model('type','App\Type');
Route::model('accommodation','App\Accommodation');
Route::model('service','App\Service');
Route::model('staff','App\Staff');
Route::model('user','App\User');
Route::model('term','App\Term');
Route::model('icon','App\Icon');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::get('/', ['as'=>'index', 'uses'=>'FrontendController@index']);
Route::get('/terms', ['as'=>'terms', 'uses'=>'FrontendController@terms']);
Route::get('attractions', ['as'=>'blog', 'uses'=>'FrontendController@blog']);
Route::get('attractions/category/{slug}', ['as'=>'blog.category', 'uses'=>'FrontendController@blogCategory']);
Route::get('attractions/post/{slug}', ['as'=>'blog.show', 'uses'=>'FrontendController@post']);

Route::get('news', ['as'=>'news', 'uses'=>'FrontendController@news']);

Route::get('galleries', ['as'=>'galleries', 'uses'=>'FrontendController@galleries']);

Route::get('event/{slug}', ['as'=>'events.show', 'uses'=>'FrontendController@eventSlug']);
Route::get('events', ['as'=>'events', 'uses'=>'FrontendController@events']);

Route::get('accommodation/{slug}', ['as'=>'room.accommodation', 'uses'=>'FrontendController@accommodation']);

Route::get('booking', ['as'=>'booking', 'uses'=>'FrontendController@booking']);

Route::get('about', ['as'=>'about', 'uses'=>'FrontendController@about']);

Route::get('contact', ['as'=>'contact', 'uses'=>'FrontendController@contact']);

Route::get('location', ['as'=>'location', 'uses'=>'FrontendController@location']);
Route::post('sendContact', ['as'=>'send.mail', 'uses'=>'FrontendController@postContact']);

//switch language. Default is english
Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);

Route::group(['middleware'=>'SentinelGuest'],function(){
	Route::get('login',['as'=>'login','uses'=>'Auth\LoginController@getSignin']);
	Route::post('postSignin', ['as'=>'postSignin'  ,'uses'=>'Auth\LoginController@postSignin']);
	Route::get('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
	Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
	Route::get('password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
	Route::post('password/reset', ['as' => 'password.request', 'uses' => 'Auth\ResetPasswordController@reset']);
});

Route::group(['middleware'=>'SentinelUser'],function(){
	Route::get('logout',['as'=>'logout','uses'=>'Auth\LoginController@getLogout']);

	Route::group(['prefix'=>'admin','as'=>'dash.'],function(){
		Route::get('/',['as'=>'index','uses'=>'DashboardController@index']);
		
		Route::group(['prefix'=>'posts','as'=>'post.'],function(){
			Route::get('/',['as'=>'index','uses'=>'PostController@index']);	
			Route::get('create',['as'=>'create','uses'=>'PostController@create']);
			Route::post('store',['as'=>'store','uses'=>'PostController@store']);
			Route::get('show/{post}',['as'=>'show','uses'=>'PostController@show']);	
			Route::get('edit/{post}',['as'=>'edit','uses'=>'PostController@edit']);	
			Route::put('update/{post}',['as'=>'update','uses'=>'PostController@update']);
			Route::get('delete/{post}',['as'=>'delete','uses'=>'PostController@destroy']);	
		});

		Route::group(['prefix'=>'categories','as'=>'category.'],function(){
			Route::get('/',['as'=>'index','uses'=>'CategoryController@index']);	
			Route::get('create',['as'=>'create','uses'=>'CategoryController@create']);
			Route::post('store',['as'=>'store','uses'=>'CategoryController@store']);
			Route::get('show/{category}',['as'=>'show','uses'=>'CategoryController@show']);	
			Route::get('edit/{category}',['as'=>'edit','uses'=>'CategoryController@edit']);	
			Route::put('update/{category}',['as'=>'update','uses'=>'CategoryController@update']);
			Route::get('delete/{category}',['as'=>'delete','uses'=>'CategoryController@destroy']);	
		});

		Route::group(['prefix'=>'events','as'=>'event.'],function(){
			Route::get('/',['as'=>'index','uses'=>'EventController@index']);	
			Route::get('create',['as'=>'create','uses'=>'EventController@create']);
			Route::post('store',['as'=>'store','uses'=>'EventController@store']);
			Route::get('show/{event}',['as'=>'show','uses'=>'EventController@show']);	
			Route::get('edit/{event}',['as'=>'edit','uses'=>'EventController@edit']);	
			Route::put('update/{event}',['as'=>'update','uses'=>'EventController@update']);
			Route::get('delete/{event}',['as'=>'delete','uses'=>'EventController@destroy']);	
		});

		Route::group(['prefix'=>'galleries','as'=>'gallery.'],function(){
			Route::get('/',['as'=>'index','uses'=>'GalleryController@index']);	
			Route::get('create',['as'=>'create','uses'=>'GalleryController@create']);
			Route::post('store',['as'=>'store','uses'=>'GalleryController@store']);
			Route::get('show/{gallery}',['as'=>'show','uses'=>'GalleryController@show']);	
			Route::get('edit/{gallery}',['as'=>'edit','uses'=>'GalleryController@edit']);	
			Route::put('update/{gallery}',['as'=>'update','uses'=>'GalleryController@update']);
			Route::get('delete/{gallery}',['as'=>'delete','uses'=>'GalleryController@destroy']);	
		});


		Route::group(['prefix'=>'accommodations','as'=>'accommodation.'],function(){
			Route::get('/',['as'=>'index','uses'=>'AccommodationController@index']);	
			Route::get('create',['as'=>'create','uses'=>'AccommodationController@create']);
			Route::post('store',['as'=>'store','uses'=>'AccommodationController@store']);
			Route::get('show/{accommodation}',['as'=>'show','uses'=>'AccommodationController@show']);	
			Route::get('edit/{accommodation}',['as'=>'edit','uses'=>'AccommodationController@edit']);	
			Route::put('update/{accommodation}',['as'=>'update','uses'=>'AccommodationController@update']);
			Route::get('delete/{accommodation}',['as'=>'delete','uses'=>'AccommodationController@destroy']);	
		});

		Route::group(['prefix'=>'typeaccommodations','as'=>'type_accommodation.'],function(){
			Route::get('/',['as'=>'index','uses'=>'TypeController@index']);	
			Route::get('create',['as'=>'create','uses'=>'TypeController@create']);
			Route::post('store',['as'=>'store','uses'=>'TypeController@store']);
			Route::get('show/{type}',['as'=>'show','uses'=>'TypeController@show']);	
			Route::get('edit/{type}',['as'=>'edit','uses'=>'TypeController@edit']);	
			Route::put('update/{type}',['as'=>'update','uses'=>'TypeController@update']);
			Route::get('delete/{type}',['as'=>'delete','uses'=>'TypeController@destroy']);	
		});

		Route::group(['prefix'=>'services','as'=>'service.'],function(){
			Route::get('/',['as'=>'index','uses'=>'ServiceController@index']);	
			Route::get('create',['as'=>'create','uses'=>'ServiceController@create']);
			Route::post('store',['as'=>'store','uses'=>'ServiceController@store']);
			Route::get('show/{service}',['as'=>'show','uses'=>'ServiceController@show']);	
			Route::get('edit/{service}',['as'=>'edit','uses'=>'ServiceController@edit']);	
			Route::put('update/{service}',['as'=>'update','uses'=>'ServiceController@update']);
			Route::get('delete/{service}',['as'=>'delete','uses'=>'ServiceController@destroy']);	
		});

		Route::group(['prefix'=>'staffs','as'=>'staff.'],function(){
			Route::get('/',['as'=>'index','uses'=>'StaffController@index']);	
			Route::get('create',['as'=>'create','uses'=>'StaffController@create']);
			Route::post('store',['as'=>'store','uses'=>'StaffController@store']);
			Route::get('show/{staff}',['as'=>'show','uses'=>'StaffController@show']);	
			Route::get('edit/{staff}',['as'=>'edit','uses'=>'StaffController@edit']);	
			Route::put('update/{staff}',['as'=>'update','uses'=>'StaffController@update']);
			Route::get('delete/{staff}',['as'=>'delete','uses'=>'StaffController@destroy']);	
		});

		Route::group(['prefix'=>'users','as'=>'user.'],function(){
			Route::get('/',['as'=>'index','uses'=>'UserController@index']);	
			Route::get('create',['as'=>'create','uses'=>'UserController@create']);
			Route::post('store',['as'=>'store','uses'=>'UserController@store']);
			//Route::get('show/{user}',['as'=>'show','uses'=>'UserController@show']);	
			Route::get('edit/{user}',['as'=>'edit','uses'=>'UserController@edit']);	
			Route::put('update/{user}',['as'=>'update','uses'=>'UserController@update']);
			Route::get('delete/{user}',['as'=>'delete','uses'=>'UserController@destroy']);	
			//Route::get('restore/{id}', array('as' => 'restore', 'uses' => 'UserController@restore'));
		});

		//role
		Route::group(['prefix'=>'roles','as'=>'role.'], function(){
			Route::get('/', array('as' => 'index', 'uses' => 'RoleController@index'));
			Route::get('create', array('as' => 'create', 'uses' => 'RoleController@create'));
			Route::post('store', array('as' => 'store', 'uses' => 'RoleController@store'));
			Route::get('edit/{id}', array('as' => 'edit', 'uses' => 'RoleController@edit'));
			Route::put('update/{id}', array('as' => 'update', 'uses' => 'RoleController@update'));
			Route::get('delete/{id}', array('as' => 'delete', 'uses' => 'RoleController@destroy'));
		});

		Route::group(['prefix'=>'terms','as'=>'term.'],function(){
			Route::get('/',['as'=>'index','uses'=>'TermController@index']);	
			Route::get('create',['as'=>'create','uses'=>'TermController@create']);
			Route::post('store',['as'=>'store','uses'=>'TermController@store']);
			Route::get('show/{term}',['as'=>'show','uses'=>'TermController@show']);	
			Route::get('edit/{term}',['as'=>'edit','uses'=>'TermController@edit']);	
			Route::put('update/{term}',['as'=>'update','uses'=>'TermController@update']);
			Route::get('delete/{term}',['as'=>'delete','uses'=>'TermController@destroy']);	
		});

		Route::group(['prefix'=>'icons','as'=>'icon.'],function(){

app/Staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Staff extends Model
{
	use SoftDeletes;
	protected $table = "staffs";
	protected $dates = ['deleted_at'];
	protected $guarded = ['id'];
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StaffRequest;
use App\Staff;

class StaffController extends Controller
{
    public function index()
    {
    	$staffs = Staff::orderBy('created_at', 'desc')->paginate(10);
    	return view('admin.staff.index',compact('staffs'));
    }

    public function create()
    {
    	return view('admin.staff.create');
    }

    public function store(StaffRequest $request)
    {
    	try {
    		$staff = new Staff;
            $staff->name = $request->name;
            $staff->description = $request->description;
            if ($file = $request->file('pic')) {
    			$fileName = $file->getClientOriginalName();
    			$extension = $file->getClientOriginalExtension() ?: 'png';
    			$folderName = '/uploads/staffs/';
    			$destinationPath = public_path() . $folderName;
    			$safeName = md5($staff->title) . '.' . $extension;
    			$file->move($destinationPath, $safeName);
    			$staff->pic = $safeName;
    		}


            $staff->save(); 
	    	return redirect()->route('dash.staff.index');
    	} catch (Exception $e) {
            return redirect()->back()->withErrors($e->getMessage());	
    	}
    	
    	
    }

    public function edit(Staff $staff)
    {
    	return view('admin.staff.edit',compact('staff'));
    }

    public function update(StaffRequest $request, Staff $staff)
    {
    	try {
             $staff->name = $request->name;
            $staff->description = $request->description;

            if ($file = $request->file('pic')) {
    			$fileName = $file->getClientOriginalName();
    			$extension = $file->getClientOriginalExtension() ?: 'png';
    			$folderName = '/uploads/staffs/';
    			$destinationPath = public_path() . $folderName;
    			$safeName = md5($staff->title) . '.' . $extension;
    			$file->move($destinationPath, $safeName);
    			$staff->pic = $safeName;
    		}

            $staff->save(); 
	    	return redirect()->route('dash.staff.index');
    	} catch (Exception $e) {
            return redirect()->back()->withErrors($e->getMessage());	
    	}
    }

    public function show(Staff $staff)
    {
        return view('admin.staff.show',compact('staff'));
    }

    public function destroy(Staff $staff)
    {
        try {
            $staff->delete();
            return redirect()->route('dash.staff.index');
        } catch (Exception $e) {
            return redirect()->back()->withErrors($e->getMessage());  
        }
    }
}

resources/views/admin/staff/create.blade.php
@extends('admin/layouts/default')

@section('css')
<link rel="stylesheet" href="{{ asset('css/jquery.filer.css') }}">
<link rel="stylesheet" href="{{ asset('css/gallery.css') }}">
@endsection

@section('body')
<main>
	<div class="breadcrumb grey lighten-3">
		<h6>Novo funcionario</h6>
	</div>

	<div class="notifications">
		@include('errors/notifications')
	</div>

	<div class="container section">
		<div class="row">
			<form id="staff" class="col s12" method="post" action="{{ route('dash.staff.store') }}" enctype="multipart/form-data">
				{{csrf_field()}}

				<div class="row">
					<div class="input-field col s12">
						<input id="name" type="text" name="name" value="{{ old('name') }}">
						<label for="name">Nome</label>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<textarea name="description" id="description" rows="10">{{ old('description') }}</textarea>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input type="file" name="pic" id="filer_input">
					</div>
				</div>

				<div class="row center">
					<div class="col s12">
						<button class="waves-effect btn black-text" type="submit">Enviar</button>
					</div>
				</div>
			</form> 
		</div>
	</div>
</main>
@endsection

@section('script')
<script src="{{ asset('js/jquery.filer.min.js') }}"></script>
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('js/staff.js') }}"></script>
@endsection

resources/views/admin/staff/edit.blade.php
@extends('admin/layouts/default')

@section('css')
<link rel="stylesheet" href="{{ asset('css/jquery.filer.css') }}">
<link rel="stylesheet" href="{{ asset('css/gallery.css') }}">
@endsection

@section('body')
<main>
	<div class="breadcrumb grey lighten-3">
		<h6>Editar funcionario</h6>
	</div>

	<div class="notifications">
		@include('errors/notifications')
	</div>

	<div class="container section">
		<div class="row">
			<form id="staff" class="col s12" method="post" action="{{ route('dash.staff.update',$staff->id) }}" enctype="multipart/form-data">
				{{csrf_field()}}

				{{ method_field('PUT')}}
				<input type="hidden" name="staff_id" value="{{$staff->id}}">
				<div class="row">
					<div class="input-field col s12">
						<input id="name" type="text" name="name" value="{{$staff->name}}">
						<label for="name">Nome</label>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s12">
						<textarea name="description" id="description" rows="10">{{ $staff->description }}</textarea>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<input type="file" name="pic" id="filer_input_edit">
					</div>
				</div>
				<div class="row center">
					<div class="col s12">
						<button class="waves-effect btn black-text" type="submit">Enviar</button>
					</div>
				</div>
			</form> 
		</div>
	</div>
</main>
@endsection

@section('script')
<script src="{{ asset('js/jquery.filer.min.js') }}"></script>
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('js/staff.js') }}"></script>
@endsection

resources/views/admin/staff/index.blade.php
@extends('admin/layouts/default')

@section('css')
@endsection

@section('body')
<main>
	<div class="breadcrumb grey lighten-3">
		<h6>Funcionarios</h6>
	</div>

	<div class="notifications">
		@include('errors/notifications')
	</div>

	<div class="fixed-action-btn">
	<a href="{{route('dash.staff.create')}}" class="btn-floating btn-large">
			<i class="large material-icons">add</i>
		</a>
	</div>

	<div class="container section">
		<div class="row">
			<div class="col s12">				
				<table class="striped">
					<thead>
						<tr>
							<th data-field="name">Nome</th>
							<th data-field="description">Descrição</th>
							<th data-field="created_at">Data de alteração</th>
							<th data-field="actions" class="right">Ações</th>
						</tr>
					</thead>

					<tbody>
						@forelse($staffs as $staff)
						<tr>
							<td>{{$staff->name}}</td>
							<td>{{$staff->description}}</td>
							<td>{{$staff->created_at}}</td>
							<td class="right">
								<a href="{{ route('dash.staff.delete',$staff->id) }}"><i class="material-icons actions right tooltipped" data-position="left" data-delay="50" data-tooltip="Excluir">delete</i></a>
								<a href="{{ route('dash.staff.edit',$staff->id) }}"><i class="material-icons actions right tooltipped" data-position="left" data-delay="50" data-tooltip="Editar">edit</i></a>
							</td>
						</tr>
						@empty
						<tr>
							<td colspan="4">
								No else staffs
							</td>
						</tr>
						@endforelse
					</tbody>
				</table>
				<div class="center">
					{{$staffs->links('vendor.pagination.materialize-pagination')}}
				</div>
			</div>
		</div>
	</div>
</main>
@endsection

@section('script')
@endsection