routes/web.php
	<?php
Route::model('post','App\Post');
Route::model('event','App\Event');
Route::model('category','App\Category');
Route::model('type','App\Type');
Route::model('accommodation','App\Accommodation');
Route::model('service','App\Service');
Route::model('staff','App\Staff');
Route::model('user','App\User');
Route::model('term','App\Term');
Route::model('icon','App\Icon');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::get('/', ['as'=>'index', 'uses'=>'FrontendController@index']);
Route::get('/terms', ['as'=>'terms', 'uses'=>'FrontendController@terms']);
Route::get('attractions', ['as'=>'blog', 'uses'=>'FrontendController@blog']);
Route::get('attractions/category/{slug}', ['as'=>'blog.category', 'uses'=>'FrontendController@blogCategory']);
Route::get('attractions/post/{slug}', ['as'=>'blog.show', 'uses'=>'FrontendController@post']);

Route::get('news', ['as'=>'news', 'uses'=>'FrontendController@news']);

Route::get('galleries', ['as'=>'galleries', 'uses'=>'FrontendController@galleries']);

Route::get('event/{slug}', ['as'=>'events.show', 'uses'=>'FrontendController@eventSlug']);
Route::get('events', ['as'=>'events', 'uses'=>'FrontendController@events']);

Route::get('accommodation/{slug}', ['as'=>'room.accommodation', 'uses'=>'FrontendController@accommodation']);

Route::get('booking', ['as'=>'booking', 'uses'=>'FrontendController@booking']);

Route::get('about', ['as'=>'about', 'uses'=>'FrontendController@about']);

Route::get('contact', ['as'=>'contact', 'uses'=>'FrontendController@contact']);

Route::get('location', ['as'=>'location', 'uses'=>'FrontendController@location']);
Route::post('sendContact', ['as'=>'send.mail', 'uses'=>'FrontendController@postContact']);

//switch language. Default is english
Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);

Route::group(['middleware'=>'SentinelGuest'],function(){
	Route::get('login',['as'=>'login','uses'=>'Auth\LoginController@getSignin']);
	Route::post('postSignin', ['as'=>'postSignin'  ,'uses'=>'Auth\LoginController@postSignin']);
	Route::get('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
	Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
	Route::get('password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
	Route::post('password/reset', ['as' => 'password.request', 'uses' => 'Auth\ResetPasswordController@reset']);
});

Route::group(['middleware'=>'SentinelUser'],function(){
	Route::get('logout',['as'=>'logout','uses'=>'Auth\LoginController@getLogout']);

	Route::group(['prefix'=>'admin','as'=>'dash.'],function(){
		Route::get('/',['as'=>'index','uses'=>'DashboardController@index']);
		
		Route::group(['prefix'=>'posts','as'=>'post.'],function(){
			Route::get('/',['as'=>'index','uses'=>'PostController@index']);	
			Route::get('create',['as'=>'create','uses'=>'PostController@create']);
			Route::post('store',['as'=>'store','uses'=>'PostController@store']);
			Route::get('show/{post}',['as'=>'show','uses'=>'PostController@show']);	
			Route::get('edit/{post}',['as'=>'edit','uses'=>'PostController@edit']);	
			Route::put('update/{post}',['as'=>'update','uses'=>'PostController@update']);
			Route::get('delete/{post}',['as'=>'delete','uses'=>'PostController@destroy']);	
		});

		Route::group(['prefix'=>'categories','as'=>'category.'],function(){
			Route::get('/',['as'=>'index','uses'=>'CategoryController@index']);	
			Route::get('create',['as'=>'create','uses'=>'CategoryController@create']);
			Route::post('store',['as'=>'store','uses'=>'CategoryController@store']);
			Route::get('show/{category}',['as'=>'show','uses'=>'CategoryController@show']);	
			Route::get('edit/{category}',['as'=>'edit','uses'=>'CategoryController@edit']);	
			Route::put('update/{category}',['as'=>'update','uses'=>'CategoryController@update']);
			Route::get('delete/{category}',['as'=>'delete','uses'=>'CategoryController@destroy']);	
		});

		Route::group(['prefix'=>'events','as'=>'event.'],function(){
			Route::get('/',['as'=>'index','uses'=>'EventController@index']);	
			Route::get('create',['as'=>'create','uses'=>'EventController@create']);
			Route::post('store',['as'=>'store','uses'=>'EventController@store']);
			Route::get('show/{event}',['as'=>'show','uses'=>'EventController@show']);	
			Route::get('edit/{event}',['as'=>'edit','uses'=>'EventController@edit']);	
			Route::put('update/{event}',['as'=>'update','uses'=>'EventController@update']);
			Route::get('delete/{event}',['as'=>'delete','uses'=>'EventController@destroy']);	
		});

		Route::group(['prefix'=>'galleries','as'=>'gallery.'],function(){
			Route::get('/',['as'=>'index','uses'=>'GalleryController@index']);	
			Route::get('create',['as'=>'create','uses'=>'GalleryController@create']);
			Route::post('store',['as'=>'store','uses'=>'GalleryController@store']);
			Route::get('show/{gallery}',['as'=>'show','uses'=>'GalleryController@show']);	
			Route::get('edit/{gallery}',['as'=>'edit','uses'=>'GalleryController@edit']);	
			Route::put('update/{gallery}',['as'=>'update','uses'=>'GalleryController@update']);
			Route::get('delete/{gallery}',['as'=>'delete','uses'=>'GalleryController@destroy']);	
		});


		Route::group(['prefix'=>'accommodations','as'=>'accommodation.'],function(){
			Route::get('/',['as'=>'index','uses'=>'AccommodationController@index']);	
			Route::get('create',['as'=>'create','uses'=>'AccommodationController@create']);
			Route::post('store',['as'=>'store','uses'=>'AccommodationController@store']);
			Route::get('show/{accommodation}',['as'=>'show','uses'=>'AccommodationController@show']);	
			Route::get('edit/{accommodation}',['as'=>'edit','uses'=>'AccommodationController@edit']);	
			Route::put('update/{accommodation}',['as'=>'update','uses'=>'AccommodationController@update']);
			Route::get('delete/{accommodation}',['as'=>'delete','uses'=>'AccommodationController@destroy']);	
		});

		Route::group(['prefix'=>'typeaccommodations','as'=>'type_accommodation.'],function(){
			Route::get('/',['as'=>'index','uses'=>'TypeController@index']);	
			Route::get('create',['as'=>'create','uses'=>'TypeController@create']);
			Route::post('store',['as'=>'store','uses'=>'TypeController@store']);
			Route::get('show/{type}',['as'=>'show','uses'=>'TypeController@show']);	
			Route::get('edit/{type}',['as'=>'edit','uses'=>'TypeController@edit']);	
			Route::put('update/{type}',['as'=>'update','uses'=>'TypeController@update']);
			Route::get('delete/{type}',['as'=>'delete','uses'=>'TypeController@destroy']);	
		});

		Route::group(['prefix'=>'services','as'=>'service.'],function(){
			Route::get('/',['as'=>'index','uses'=>'ServiceController@index']);	
			Route::get('create',['as'=>'create','uses'=>'ServiceController@create']);
			Route::post('store',['as'=>'store','uses'=>'ServiceController@store']);
			Route::get('show/{service}',['as'=>'show','uses'=>'ServiceController@show']);	
			Route::get('edit/{service}',['as'=>'edit','uses'=>'ServiceController@edit']);	
			Route::put('update/{service}',['as'=>'update','uses'=>'ServiceController@update']);
			Route::get('delete/{service}',['as'=>'delete','uses'=>'ServiceController@destroy']);	
		});

		Route::group(['prefix'=>'staffs','as'=>'staff.'],function(){
			Route::get('/',['as'=>'index','uses'=>'StaffController@index']);	
			Route::get('create',['as'=>'create','uses'=>'StaffController@create']);
			Route::post('store',['as'=>'store','uses'=>'StaffController@store']);
			Route::get('show/{staff}',['as'=>'show','uses'=>'StaffController@show']);	
			Route::get('edit/{staff}',['as'=>'edit','uses'=>'StaffController@edit']);	
			Route::put('update/{staff}',['as'=>'update','uses'=>'StaffController@update']);
			Route::get('delete/{staff}',['as'=>'delete','uses'=>'StaffController@destroy']);	
		});

		Route::group(['prefix'=>'users','as'=>'user.'],function(){
			Route::get('/',['as'=>'index','uses'=>'UserController@index']);	
			Route::get('create',['as'=>'create','uses'=>'UserController@create']);
			Route::post('store',['as'=>'store','uses'=>'UserController@store']);
			//Route::get('show/{user}',['as'=>'show','uses'=>'UserController@show']);	
			Route::get('edit/{user}',['as'=>'edit','uses'=>'UserController@edit']);	
			Route::put('update/{user}',['as'=>'update','uses'=>'UserController@update']);
			Route::get('delete/{user}',['as'=>'delete','uses'=>'UserController@destroy']);	
			//Route::get('restore/{id}', array('as' => 'restore', 'uses' => 'UserController@restore'));
		});

		//role
		Route::group(['prefix'=>'roles','as'=>'role.'], function(){
			Route::get('/', array('as' => 'index', 'uses' => 'RoleController@index'));
			Route::get('create', array('as' => 'create', 'uses' => 'RoleController@create'));
			Route::post('store', array('as' => 'store', 'uses' => 'RoleController@store'));
			Route::get('edit/{id}', array('as' => 'edit', 'uses' => 'RoleController@edit'));
			Route::put('update/{id}', array('as' => 'update', 'uses' => 'RoleController@update'));
			Route::get('delete/{id}', array('as' => 'delete', 'uses' => 'RoleController@destroy'));
		});

		Route::group(['prefix'=>'terms','as'=>'term.'],function(){
			Route::get('/',['as'=>'index','uses'=>'TermController@index']);	
			Route::get('create',['as'=>'create','uses'=>'TermController@create']);
			Route::post('store',['as'=>'store','uses'=>'TermController@store']);
			Route::get('show/{term}',['as'=>'show','uses'=>'TermController@show']);	
			Route::get('edit/{term}',['as'=>'edit','uses'=>'TermController@edit']);	
			Route::put('update/{term}',['as'=>'update','uses'=>'TermController@update']);
			Route::get('delete/{term}',['as'=>'delete','uses'=>'TermController@destroy']);	
		});

		Route::group(['prefix'=>'icons','as'=>'icon.'],function(){

app/Term.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;
use App\Traits\LangTrait;

class Term extends Model
{
    use LangTrait;
    
    protected $langOrderBy = 'term_id';
    protected $fillable = ['icon'];
    
    public function translations()
    {
        return $this->hasMany('App\TermTranslation');
    }

    // public function translation($language = null)
    // {
    //     if ($language == null) {
    //         $language = App::getLocale();
    //     }
    //     return $this->translations()->where('language', '=', $language)->orderBy('term_id','asc')->first();
    // }
}

app/Http/Controllers/TermController.php
<?php

namespace App\Http\Controllers;

use App\Term;
use App\TermTranslation;
use App\Http\Requests\TermRequest;
use App\Icon;
class TermController extends Controller
{
    public function index()
    {
    	$terms = Term::orderBy('created_at', 'desc')->paginate(10);
    	return view('admin.terms.index',compact('terms'));
    }

    public function create()
    {
        $files = Icon::all();
    	return view('admin.terms.create',compact('files'));
    }

    public function store(TermRequest $request)
    {
    	try {
    		$term = new Term;
	    	$term->icon = $request->get('icon');

            $languages = array();
            $trans_pt = new TermTranslation;
            $trans_pt->title = $request->get('portuguese_title');
            $trans_pt->description = $request->get('portuguese_description');
            $trans_pt->language = 'pt';
            $languages[]=$trans_pt;

            $trans_en = new TermTranslation;
            $trans_en->title = $request->get('english_title');
            $trans_en->description = $request->get('english_description');
            $trans_en->language = 'en';
            $languages[]=$trans_en;

            $trans_es = new TermTranslation;
            $trans_es->title = $request->get('spanish_title');
            $trans_es->description = $request->get('spanish_description');
            $trans_es->language = 'es';
            $languages[]=$trans_es;
            
            $term->save();   
            $term->translations()->saveMany($languages);
	    	
	    	return redirect()->route('dash.term.index');
    	} catch (Exception $e) {
            return redirect()->back()->withErrors($e->getMessage());	
    	}
    	
    	
    }

    public function edit(Term $term)
    {
        $files = Icon::all();
    	return view('admin.terms.edit',compact('term','files'));
    }

    public function update(TermRequest $request, Term $term)
    {
    	try {
	    	$term->icon = $request->get('icon');

			$languages = array();
            $trans_pt = new TermTranslation;
            $trans_pt->title = $request->get('portuguese_title');
            $trans_pt->description = $request->get('portuguese_description');
            $trans_pt->language = 'pt';
            $languages[]=$trans_pt;

            $trans_en = new TermTranslation;
            $trans_en->title = $request->get('english_title');
            $trans_en->description = $request->get('english_description');
            $trans_en->language = 'en';
            $languages[]=$trans_en;

            $trans_es = new TermTranslation;
            $trans_es->title = $request->get('spanish_title');
            $trans_es->description = $request->get('spanish_description');
            $trans_es->language = 'es';
            $languages[]=$trans_es;
            

            $term->save();
            $term->translations()->saveMany($languages);
	    		
	    	return redirect()->route('dash.term.index');
    	} catch (Exception $e) {
            return redirect()->back()->withErrors($e->getMessage());	
    	}
    }

    public function show(Term $term)
    {
        return view('admin.terms.show',compact('term'));
    }


    public function destroy(Term $term)
    {
        try {
            $term->delete();
            return redirect()->route('dash.term.index');
        } catch (Exception $e) {
            return redirect()->back()->withErrors($e->getMessage());  
        }
    }
}

resources/views/admin/terms/create.blade.php
@extends('admin/layouts/default')

@section('css')
@endsection

@section('body')
<main>
	<div class="breadcrumb grey lighten-3">
		<h6>Nova regra</h6>
	</div>

	<div class="notifications">
		@include('errors/notifications')
	</div>

	<div class="container section">
		<div class="row">
			<div class="col s12">
				<ul class="tabs">
					<li class="tab col s4"><a class="active" href="#portuguese">Português</a></li>
					<li class="tab col s4"><a href="#english">Inglês</a></li>
					<li class="tab col s4"><a href="#spanish">Espanhol</a></li>
				</ul>
			</div>
			<form class="col s12" method="post" action="{{ route('dash.term.store') }}" enctype="multipart/form-data">
				{{ csrf_field() }}

				<div id="portuguese">
					<div class="row">
						<div class="input-field col s12">
							<input id="title" type="text" name="portuguese_title" value="{{ old('portuguese_title') }}">
							<label for="title">Nome</label>
						</div>
					</div>

					<div class="row">
						<div class="input-field col s12">
							<textarea name="portuguese_description" id="portuguese_description" rows="10">{{ old('portuguese_description') }}</textarea>
						</div>
					</div>
				</div>

				<div id="english">
					<div class="row">
						<div class="input-field col s12">
							<input id="title" type="text" name="english_title" value="{{ old('english_title') }}">
							<label for="title">Nome</label>
						</div>
					</div>

					<div class="row">
						<div class="input-field col s12">
							<textarea name="english_description" id="english_description" rows="10">{{ old('english_description') }}</textarea>
						</div>
					</div>
				</div>

				<div id="spanish">
					<div class="row">
						<div class="input-field col s12">
							<input id="title" type="text" name="spanish_title" value="{{ old('spanish_title') }}">
							<label for="title">Nome</label>
						</div>
					</div>

					<div class="row">
						<div class="input-field col s12">
							<textarea name="spanish_description" id="spanish_description" rows="10">{{ old('spanish_description') }}</textarea>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col s12">
						<div class="input-field col s12">
							<select class="icons" name="icon">
								<option value="" disabled selected>Escola um ícone para a regra</option>
								@forelse($files as $file)
								<option class="left" value="{{$file->path}}" data-icon="/images/icons/{{$file->path}}">{{$file->name}}</option>
								@empty
								@endforelse
							</select>
						</div>
					</div>
				</div>
				<div class="row center">
					<div class="col s12">
						<button class="waves-effect btn black-text" type="submit">Enviar</button>
					</div>
				</div>
			</form> 
		</div>
	</div>
</main>
@endsection

@section('script')
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('js/term.js') }}"></script>
@endsection

resources/views/admin/terms/edit.blade.php
@extends('admin/layouts/default')

@section('css')
@endsection

@section('body')
<main>
	<div class="breadcrumb grey lighten-3">
		<h6>Nova regra</h6>
	</div>

	<div class="notifications">
		@include('errors/notifications')
	</div>

	<div class="container section">
		<div class="row">
			<div class="col s12">
				<ul class="tabs">
					<li class="tab col s4"><a class="active" href="#portuguese">Português</a></li>
					<li class="tab col s4"><a href="#english">Inglês</a></li>
					<li class="tab col s4"><a href="#spanish">Espanhol</a></li>
				</ul>
			</div>
			<form class="col s12" method="post" action="{{ route('dash.term.update', $term->id) }}" enctype="multipart/form-data">
				{{ csrf_field() }}
				{{ method_field('PUT')}}
				<div id="portuguese">
					<div class="row">
						<div class="input-field col s12">
							<input id="title" type="text" name="portuguese_title" value="{{$term->translation('pt')->title}}">
							<label for="title">Título</label>
						</div>
					</div>

					<div class="row">
						<div class="input-field col s12">
							<textarea id="portuguese_description" class="materialize-textarea" name="portuguese_description">{{$term->translation('pt')->description}}</textarea>
						</div>
					</div>
				</div>

				<div id="english">
					<div class="row">
						<div class="input-field col s12">
							<input id="title" type="text" name="english_title" value="{{$term->translation('en')->title}}">
							<label for="title">Título</label>
						</div>
					</div>

					<div class="row">
						<div class="input-field col s12">
							<textarea name="english_description" id="english_description" rows="10">{{$term->translation('en')->description}}</textarea>
						</div>
					</div>
				</div>

				<div id="spanish">
					<div class="row">
						<div class="input-field col s12">
							<input id="title" type="text" name="spanish_title" value="{{$term->translation('es')->title}}">
							<label for="title">Título</label>
						</div>
					</div>

					<div class="row">
						<div class="input-field col s12">
							<textarea id="spanish_description" class="materialize-textarea" name="spanish_description">{{$term->translation('es')->description}}</textarea>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="input-field col s12">
						<select class="icons" name="icon">
							<option value="" disabled selected>Escola um ícone para a regra</option>
							@forelse($files as $file)
							@if($term->icon == $file->path)
							<option class="left" value="{{$file->path}}" data-icon="/images/icons/{{$file->path}}" selected>{{$file->name}}</option>
							@else
							<option class="left" value="{{$file->path}}" data-icon="/images/icons/{{$file->path}}">{{$file->name}}</option>
							@endif
							@empty

							@endforelse
						</select>
					</div>
				</div>

				<div class="row center">
					<div class="col s12">
						<button class="waves-effect btn black-text" type="submit">Enviar</button>
					</div>
				</div>
			</form> 
		</div>
	</div>
</main>
@endsection

@section('script')
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('js/term.js') }}"></script>
@endsection

resources/views/admin/terms/index.blade.php
@extends('admin/layouts/default')

@section('css')
@endsection

@section('body')
<main>
	<div class="breadcrumb grey lighten-3">
		<h6>Termos e condições</h6>
	</div>

	<div class="notifications">
		@include('errors/notifications')
	</div>

	<div class="fixed-action-btn">
	<a href="{{route('dash.term.create')}}" class="btn-floating btn-large">
			<i class="large material-icons">add</i>
		</a>
	</div>

	<div class="container section">
		<div class="row">
			<div class="col s12">				
				<table class="striped">
					<thead>
						<tr>
							<th data-field="title">Nome</th>
							<th data-field="icon">Icone</th>
							<th data-field="actions" class="right">Ações</th>
						</tr>
					</thead>

					<tbody>
						@forelse($terms as $term)
						<tr>
							<td>{{$term->translation('pt')->title}}</td>
							<td> <img class="icon" src="{{ asset('images/icons/'.$term->icon) }}"></td>
							<td class="right">
								<a href="{{ route('dash.term.delete',$term->id) }}"><i class="material-icons actions right tooltipped" data-position="left" data-delay="50" data-tooltip="Excluir">delete</i></a>
								<a href="{{ route('dash.term.edit',$term->id) }}"><i class="material-icons actions right tooltipped" data-position="left" data-delay="50" data-tooltip="Editar">edit</i></a>
							</td>
						</tr>
						@empty
						<tr>
							<td colspan="3">
								No else terms
							</td>
						</tr>
						@endforelse
					</tbody>
				</table>
				<div class="center">
					{{$terms->links('vendor.pagination.materialize-pagination')}}
				</div>
			</div>
		</div>
	</div>
</main>
@endsection

@section('script')
@endsection